from django.urls import path
from .views import (
    registration_admin_dashboard,
    approve_user_registration,
    manage_registration_users,
    toggle_permission, 
    make_registration_admin,
    remove_registration_admin,
    remove_user_from_module,
    reset_user_password,
    view_students,
    student_detail,
    archive_student,
    restore_student,
    download_students_pdf,
    register_student,
    registration_home,
    manage_equipment,  
    archived_students,
    delete_equipment,
    edit_equipment, 
    student_report_pdf,
    import_students_excel,
    download_import_template,
   
)

urlpatterns = [
    path('dashboard/', registration_home, name='registration_dashboard'),
    path('', registration_home, name='registration_home'),
    path('admin/', registration_admin_dashboard, name='registration_admin_dashboard'),
    path('approve/<int:usermodule_id>/', approve_user_registration, name='approve_user_registration'),
    path('users/', manage_registration_users, name='manage_registration_users'),
    path('toggle/<int:usermodule_id>/<str:perm>/', toggle_permission, name='toggle_permission'),
    path('make-admin/<int:usermodule_id>/', make_registration_admin, name='make_registration_admin'),
    path('remove-admin/<int:usermodule_id>/', remove_registration_admin, name='remove_registration_admin'),
    path('remove-user/<int:usermodule_id>/', remove_user_from_module, name='remove_user_from_module'),
    path('reset-password/<int:user_id>/', reset_user_password, name='reset_user_password'),
    path('students/', view_students, name='view_students'),
    path('student/<int:student_id>/', student_detail, name='student_detail'),
    path('archive/<int:student_id>/', archive_student, name='archive_student'),
    path('restore/<int:student_id>/', restore_student, name='restore_student'),
    path('download/pdf/', download_students_pdf, name='download_students_pdf'),
    path('register/', register_student, name='register_student'),
    path('equipment/', manage_equipment, name='manage_equipment'), 
    path('archived/', archived_students, name='archived_students'), 
    path('equipment/<int:equipment_id>/edit/', edit_equipment, name='edit_equipment'),
    path('equipment/<int:equipment_id>/delete/', delete_equipment, name='delete_equipment'),
    path('student/<int:student_id>/report/', student_report_pdf, name='student_report_pdf'),
    path('import/', import_students_excel, name='import_students'),
    path('import/template/', download_import_template, name='download_import_template'),
    
]