# Generated by Django 6.0.3 on 2026-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_module_usermodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='is_exam_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
