# Generated by Django 6.0.3 on 2026-04-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('registration', '0003_student_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='disciplinecase',
            options={'ordering': ['-date_reported']},
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='case_type',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='date_of_incident',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='severity_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['status'], name='discipline__status_545cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['case_type'], name='discipline__case_ty_56722a_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['is_archived'], name='discipline__is_arch_fa5786_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['date_reported'], name='discipline__date_re_b8d3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['date_of_incident'], name='discipline__date_of_aaa957_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['student', 'status'], name='discipline__student_540815_idx'),
        ),
        migrations.AddField(
            model_name='disciplineauditlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='discipline.disciplinecase'),
        ),
        migrations.AddField(
            model_name='disciplineauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='disciplineauditlog',
            index=models.Index(fields=['timestamp'], name='discipline__timesta_bba5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineauditlog',
            index=models.Index(fields=['action'], name='discipline__action_b5caf6_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineauditlog',
            index=models.Index(fields=['case'], name='discipline__case_id_1080b8_idx'),
        ),
    ]
