# Generated by Django 6.0.3 on 2026-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_suspensionrecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suspensionrecord',
            index=models.Index(fields=['status'], name='discipline__status_0617f5_idx'),
        ),
        migrations.AddIndex(
            model_name='suspensionrecord',
            index=models.Index(fields=['start_date'], name='discipline__start_d_0de358_idx'),
        ),
        migrations.AddIndex(
            model_name='suspensionrecord',
            index=models.Index(fields=['end_date'], name='discipline__end_dat_aaf0a1_idx'),
        ),
    ]
