# Generated by Django 6.0.3 on 2026-05-01 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0004_suspensionrecord_discipline__status_0617f5_idx_and_more'),
        ('registration', '0003_student_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecase',
            name='action_type',
            field=models.CharField(choices=[('warning', 'Warning'), ('punishment', 'Punishment'), ('suspension', 'Suspension')], db_index=True, default='warning', max_length=20),
        ),
        migrations.AddIndex(
            model_name='disciplinecase',
            index=models.Index(fields=['action_type'], name='discipline__action__ac2255_idx'),
        ),
    ]
