# Generated by Django 6.0.3 on 2026-05-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0005_disciplinecase_action_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disciplinecase',
            name='discipline__action__ac2255_idx',
        ),
    ]
