# Generated by Django 6.0.3 on 2026-08-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0006_remove_disciplinecase_discipline__action__ac2255_idx'),
        ('registration', '0007_alter_studentclasshistory_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline_cases', to='registration.student'),
        ),
    ]
