# Generated by Django 6.0.3 on 2026-04-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_academicyear_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={},
        ),
    ]
