# Generated by Django 6.0.3 on 2026-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_academicyear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
