# Generated by Django 6.0.3 on 2026-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_studentmark_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10),
        ),
    ]
