# Generated by Django 6.0.3 on 2026-04-15 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_studentmark_status'),
        ('registration', '0003_student_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'exam', 'subject', 'paper', 'uploaded_by')},
        ),
    ]
