# Generated by Django 6.0.3 on 2026-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_result_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3'), ('MID_TERM', 'Mid Term'), ('MOCK', 'Mock'), ('PRE_NECTA', 'Pre-Necta'), ('FINAL', 'Final')], default='TERM_1', max_length=20),
        ),
    ]
