# Generated by Django 6.0.3 on 2026-04-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_exam_term'),
        ('registration', '0003_student_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='level',
            field=models.CharField(choices=[('O', 'O-Level'), ('A', 'A-Level')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersubjectrequest',
            name='level',
            field=models.CharField(choices=[('O', 'O-Level'), ('A', 'A-Level')], default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('O', 'O-Level'), ('A', 'A-Level')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('O', 'O-Level'), ('A', 'A-Level')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'exam', 'subject', 'paper')},
        ),
    ]
