# Generated by Django 6.0.3 on 2026-04-27 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_marksubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combination',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='combination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combination',
            name='subjects',
            field=models.ManyToManyField(limit_choices_to={'level': 'A'}, to='academic.subject'),
        ),
    ]
