# Generated by Django 6.0.3 on 2026-04-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_combination_options_combination_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='status',
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='level',
            field=models.CharField(choices=[('O', 'O-Level'), ('A', 'A-Level')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='teachersubjectrequest',
            name='level',
            field=models.CharField(choices=[('O', 'O-Level'), ('A', 'A-Level')], editable=False, max_length=10),
        ),
    ]
