# Generated by Django 6.0.3 on 2026-04-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_studentmark_is_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksubmission',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='marksubmission',
            name='locked_at',
        ),
    ]
