# Generated by Django 6.0.3 on 2026-04-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_remove_marksubmission_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='max_marks',
            field=models.FloatField(default=100),
        ),
    ]
