# Generated by Django 6.0.3 on 2026-08-02 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_add_query_indexes'),
        ('registration', '0006_promotionbatch_studentclasshistory_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentmark',
            constraint=models.UniqueConstraint(condition=models.Q(('paper__isnull', False)), fields=('student', 'exam', 'subject', 'paper'), name='acad_mark_unique_with_paper'),
        ),
        migrations.AddConstraint(
            model_name='studentmark',
            constraint=models.UniqueConstraint(condition=models.Q(('paper__isnull', True)), fields=('student', 'exam', 'subject'), name='acad_mark_unique_without_paper'),
        ),
    ]
