# Generated by Django 6.0.3 on 2026-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('student_class', models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5'), ('Form 6', 'Form 6')], max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('date_of_admission', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('tribe', models.CharField(blank=True, max_length=100)),
                ('last_school_attended', models.CharField(blank=True, max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_phone2', models.CharField(blank=True, max_length=20)),
                ('nearby_person_phone', models.CharField(blank=True, max_length=20)),
                ('health_status', models.CharField(max_length=50)),
                ('school_status', models.CharField(default='Active', max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipments', models.ManyToManyField(blank=True, to='registration.equipment')),
            ],
        ),
    ]
