# Generated by Django 6.0.3 on 2026-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_status',
            field=models.CharField(choices=[('Fit', 'Fit'), ('Sick', 'Sick'), ('Special Needs', 'Special Needs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Graduated', 'Graduated')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('PCB', 'PCB'), ('PCM', 'PCM'), ('PMC', 'PMC'), ('CBG', 'CBG'), ('EGM', 'EGM'), ('HGK', 'HGK'), ('HGL', 'HGL')], max_length=10),
        ),
    ]
