# Generated by Django 6.0.3 on 2026-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_student_gender_alter_student_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
