# Generated by Django 6.0.3 on 2026-08-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_promotionbatch_studentclasshistory_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasshistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_history', to='registration.student'),
        ),
    ]
