# Generated by Django 6.0.3 on 2026-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduatecollection',
            old_name='date_collected',
            new_name='date_issued',
        ),
        migrations.AddField(
            model_name='graduatecollection',
            name='is_received_at_school',
            field=models.BooleanField(default=False, help_text='Mark True when the batch arrives from NECTA'),
        ),
        migrations.AddField(
            model_name='graduatecollection',
            name='necta_certificate_no',
            field=models.CharField(blank=True, help_text='Official NECTA Certificate Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graduatecollection',
            name='necta_result_slip_no',
            field=models.CharField(blank=True, help_text='Official NECTA Result Slip Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graduatecollection',
            name='certificate_collected',
            field=models.BooleanField(default=False, verbose_name='Collected by Student'),
        ),
        migrations.AlterField(
            model_name='graduatecollection',
            name='result_slip_collected',
            field=models.BooleanField(default=False, verbose_name='Collected by Student'),
        ),
    ]
