# Generated by Django 6.0.3 on 2026-08-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_collection_availability_indexes'),
        ('registration', '0007_alter_studentclasshistory_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatecollection',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_record', to='registration.student'),
        ),
    ]
