# Generated by Django 6.0.3 on 2026-08-02 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0007_alter_studentclasshistory_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(help_text='e.g. Headache, Fever, Injury', max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('referred_to_hospital', models.BooleanField(default=False)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_visits', to='registration.student')),
            ],
            options={
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['student', 'visit_date'], name='health_visit_student_date_idx'), models.Index(fields=['follow_up_required', 'follow_up_date'], name='health_visit_followup_idx')],
            },
        ),
    ]
